/****** Object:  Table [dbo].[TLog]    Script Date: 06/03/2025 14:12:34 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TLog]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TLog](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Date] [datetime] NOT NULL,
	[Before] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
	[After] [varchar](1000) COLLATE SQL_Latin1_General_CP1_CI_AI NOT NULL,
 CONSTRAINT [PK_TLog] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
END
GO

IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[DF_TLog_Date]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TLog] ADD  CONSTRAINT [DF_TLog_Date]  DEFAULT (getdate()) FOR [Date]
END
GO


